### ISSUE TITLE
Having issues during install

### ISSUE THREAD

**Issue by CornerJunky** [DeskTranslate/DeskTranslate#16]
I am new to py and i am running into some issues with this install. I think its related to the version I am using, but need some assistance getting this running. 

Here is the error I am getting
 error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Users\stali\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\stali\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\stali\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

I've tried several different versions of setuptool and this one gives me the fewest errors. Any assistance would be appreciated.

**Comment by hua-lun** [comment]
Hi @CornerJunky 

Thanks for checking out our project!

Our current code was written with Python 3.11. It seems that you are using Python 3.12. 
There might be compatibility issues. 

Which commands / steps did you take to get this error?

These are some ideas I can think of to debug:
- Download Python 3.11 and create a virtual environment and specify to use this version (to be done in the downloaded source code's directory
-  Activate the virtual environment and continue the steps as written in the main page

Alternative, you may consider downloading our application for use.
https://github.com/DeskTranslate/DeskTranslate/releases/tag/1.1a
